### ISSUE TITLE
Counter is incrementing more than allowed for each phase

### ISSUE THREAD

**Issue by ibrahimahmed** [We-Bump/Lighthouse-mint-ui#2]

**Comment by ibrahimahmed** [comment]
![image](https://github.com/We-Bump/Lighthouse-mint-ui/assets/17072421/3f52fcf0-01e7-4ecc-8614-5d17bc53bb8d)

**Comment by celsosa** [comment]
you can change  defaultValue to:
`defaultValue={amount || 1}`

and add a condition on incrementAmount (in this example, 10 is the max mintable number per wallet)

`  const incrementAmount = () => {
    if (amount < 10 - myMintedNfts?.length && amount < 10) {
      amountInput.current.value = amount + 1
      setAmount(amount + 1)
    }
  }`

**Comment by md-rifatkhan** [comment]
@ibrahimahmed how did you change the backround
