### ISSUE TITLE
Unable to `npm start`

### ISSUE THREAD

**Issue by SkyYap** [We-Bump/Lighthouse-mint-ui#4]
```
WARNING in ./node_modules/cosmjs-types/tendermint/version/types.js        
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):       
Failed to parse source map from 'C:\Users\sk_16\Documents\GitHub\Lighthouse-mint-ui\node_modules\src\tendermint\version\types.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\sk_16\Documents\GitHub\Lighthouse-mint-ui\node_modules\src\tendermint\version\types.ts'

webpack compiled with 216 warnings
```

The frontend and connect wallet is function correctly but the middle screen just keep showing loading screen. I run `npm start` and there are plenty warnings coming out. How can I fix this issue?

**Comment by SahilDhingraa** [comment]
I'm also facing same issues and it showing an error in socketwrapper file, but that file doesn't exist.

![image](https://github.com/We-Bump/Lighthouse-mint-ui/assets/92306979/34df4a8d-2e98-4ebd-b5de-167466dea1e0)
![image](https://github.com/We-Bump/Lighthouse-mint-ui/assets/92306979/0b8290e3-c7bc-4a99-a09a-338b86e9d353)

**Comment by SkyYap** [comment]
Solved the issue by adding rpc.

**Comment by SahilDhingraa** [comment]
@SkyYap hi can you tell me where to add

**Comment by SkyYap** [comment]
> @SkyYap hi can you tell me where to add

Hi, I think we didn't face the same issue. But for RPC, it is in config.json. I am using `https://rpc.atlantic-2.seinetwork.io` as RPC. Not sure with your part. But do join Discord, the community there do provide support there.

**Comment by SahilDhingraa** [comment]
ok brother
